Mongo:
  dbHost: localhost
  dbPort: 27017 
  database: optymetrics

CoreDb:
  connectionString: postgres://postgres:optify@localhost:5432/lt_optifydb1

AspenDb:
  connectionString: postgres://postgres:optify@aspen.optify.net:5432/t_optifydb1

Auth:
  sessionSecret: 'This is my SUPER secret session key'
  passwordSalt: 'It need more spice! I could just cry.'
